### ISSUE TITLE
本と章がずれている

### ISSUE THREAD

**Issue by yamoridon** [peaks-cc/iOS_architecture_samplecode#8]
本では 8 章が Flux の章になっていますがサンプルコードは 08 ディレクトリが Clean Architecture になっており 09 ディレクトリが Flux になっています。それ以降の章も本とサンプルコードのディレクトリがずれているようです。

**Comment by hirohitokato** [comment]
@yamoridon ご指摘ありがとうございます。サンプルコード作成後に本の章構成を変更したのですが、こちらはそのままになってしまっていました。
修正しますね。

**Comment by yamoridon** [comment]
ご対応ありがとうございました！
